# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/naif/Documents/squeezeCNN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/naif/Documents/squeezeCNN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/naif/Documents/squeezeCNN/CMakeFiles /home/naif/Documents/squeezeCNN/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/naif/Documents/squeezeCNN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named squeezecnn

# Build rule for target.
squeezecnn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 squeezecnn
.PHONY : squeezecnn

# fast build rule for target.
squeezecnn/fast:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/build
.PHONY : squeezecnn/fast

face_extraction.o: face_extraction.cpp.o

.PHONY : face_extraction.o

# target to build an object file
face_extraction.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/face_extraction.cpp.o
.PHONY : face_extraction.cpp.o

face_extraction.i: face_extraction.cpp.i

.PHONY : face_extraction.i

# target to preprocess a source file
face_extraction.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/face_extraction.cpp.i
.PHONY : face_extraction.cpp.i

face_extraction.s: face_extraction.cpp.s

.PHONY : face_extraction.s

# target to generate assembly for a file
face_extraction.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/face_extraction.cpp.s
.PHONY : face_extraction.cpp.s

mainAlgo.o: mainAlgo.cpp.o

.PHONY : mainAlgo.o

# target to build an object file
mainAlgo.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/mainAlgo.cpp.o
.PHONY : mainAlgo.cpp.o

mainAlgo.i: mainAlgo.cpp.i

.PHONY : mainAlgo.i

# target to preprocess a source file
mainAlgo.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/mainAlgo.cpp.i
.PHONY : mainAlgo.cpp.i

mainAlgo.s: mainAlgo.cpp.s

.PHONY : mainAlgo.s

# target to generate assembly for a file
mainAlgo.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/mainAlgo.cpp.s
.PHONY : mainAlgo.cpp.s

training_generator.o: training_generator.cpp.o

.PHONY : training_generator.o

# target to build an object file
training_generator.cpp.o:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/training_generator.cpp.o
.PHONY : training_generator.cpp.o

training_generator.i: training_generator.cpp.i

.PHONY : training_generator.i

# target to preprocess a source file
training_generator.cpp.i:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/training_generator.cpp.i
.PHONY : training_generator.cpp.i

training_generator.s: training_generator.cpp.s

.PHONY : training_generator.s

# target to generate assembly for a file
training_generator.cpp.s:
	$(MAKE) -f CMakeFiles/squeezecnn.dir/build.make CMakeFiles/squeezecnn.dir/training_generator.cpp.s
.PHONY : training_generator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... squeezecnn"
	@echo "... edit_cache"
	@echo "... face_extraction.o"
	@echo "... face_extraction.i"
	@echo "... face_extraction.s"
	@echo "... mainAlgo.o"
	@echo "... mainAlgo.i"
	@echo "... mainAlgo.s"
	@echo "... training_generator.o"
	@echo "... training_generator.i"
	@echo "... training_generator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

